set_property PACKAGE_PIN W11 [get_ports {ps_emio_tri_io[0]}]
set_property PACKAGE_PIN V11 [get_ports {ps_emio_tri_io[1]}]
set_property PACKAGE_PIN Y13 [get_ports {ps_emio_tri_io[2]}]
set_property PACKAGE_PIN Y12 [get_ports {ps_emio_tri_io[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {ps_emio_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ps_emio_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ps_emio_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ps_emio_tri_io[3]}]

set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS true [current_design]




set_property IOSTANDARD LVCMOS33 [get_ports ADC1_ADS5547_reset]
set_property IOSTANDARD LVCMOS33 [get_ports ADC1_OVR]
set_property IOSTANDARD LVCMOS33 [get_ports ADC1_SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports ADC1_SDATA]
set_property IOSTANDARD LVCMOS33 [get_ports ADC1_SEN]




set_property IOSTANDARD LVDS_25 [get_ports ADC1_CLK_P]

set_property IOSTANDARD LVDS_25 [get_ports ADC1_CLK_N]



set_property IOSTANDARD LVDS_25 [get_ports {ADC1_DATA_P[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC1_DATA_P[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC1_DATA_P[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC1_DATA_P[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC1_DATA_P[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC1_DATA_P[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC1_DATA_P[0]}]

set_property PACKAGE_PIN C6 [get_ports CLK_i]
set_property IOSTANDARD LVCMOS33 [get_ports CLK_i]
set_property PACKAGE_PIN G8 [get_ports OE_N_o]
set_property IOSTANDARD LVCMOS33 [get_ports OE_N_o]
set_property PACKAGE_PIN E7 [get_ports RD_N_o]
set_property IOSTANDARD LVCMOS33 [get_ports RD_N_o]
set_property PACKAGE_PIN G3 [get_ports RXF_N_i]
set_property IOSTANDARD LVCMOS33 [get_ports RXF_N_i]
set_property PACKAGE_PIN G2 [get_ports SIWU_N_o]
set_property PACKAGE_PIN E5 [get_ports TXE_N_i]
set_property IOSTANDARD LVCMOS33 [get_ports SIWU_N_o]
set_property IOSTANDARD LVCMOS33 [get_ports TXE_N_i]
set_property PACKAGE_PIN F7 [get_ports WR_N_o]
set_property IOSTANDARD LVCMOS33 [get_ports WR_N_o]
set_property PACKAGE_PIN G7 [get_ports WAKEUP_o]
set_property IOSTANDARD LVCMOS33 [get_ports WAKEUP_o]
set_property PACKAGE_PIN D8 [get_ports {GPIO_o[1]}]
set_property PACKAGE_PIN E8 [get_ports {GPIO_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_o[0]}]
set_property PACKAGE_PIN H6 [get_ports {DATA_io[31]}]
set_property PACKAGE_PIN B8 [get_ports {DATA_io[30]}]
set_property PACKAGE_PIN C8 [get_ports {DATA_io[29]}]
set_property PACKAGE_PIN D6 [get_ports {DATA_io[28]}]
set_property PACKAGE_PIN D7 [get_ports {DATA_io[27]}]
set_property PACKAGE_PIN B6 [get_ports {DATA_io[26]}]
set_property PACKAGE_PIN B7 [get_ports {DATA_io[25]}]
set_property PACKAGE_PIN B3 [get_ports {DATA_io[24]}]
set_property PACKAGE_PIN B4 [get_ports {DATA_io[23]}]
set_property PACKAGE_PIN A6 [get_ports {DATA_io[22]}]
set_property PACKAGE_PIN A7 [get_ports {DATA_io[21]}]
set_property PACKAGE_PIN C3 [get_ports {DATA_io[20]}]
set_property PACKAGE_PIN D3 [get_ports {DATA_io[19]}]
set_property PACKAGE_PIN A5 [get_ports {DATA_io[17]}]
set_property PACKAGE_PIN C5 [get_ports {DATA_io[16]}]
set_property PACKAGE_PIN F2 [get_ports {DATA_io[15]}]
set_property PACKAGE_PIN A1 [get_ports {DATA_io[14]}]
set_property PACKAGE_PIN A2 [get_ports {DATA_io[13]}]
set_property PACKAGE_PIN B1 [get_ports {DATA_io[12]}]
set_property PACKAGE_PIN B2 [get_ports {DATA_io[11]}]
set_property PACKAGE_PIN C1 [get_ports {DATA_io[9]}]
set_property PACKAGE_PIN G4 [get_ports {DATA_io[10]}]
set_property PACKAGE_PIN D1 [get_ports {DATA_io[8]}]
set_property PACKAGE_PIN C4 [get_ports {DATA_io[7]}]
set_property PACKAGE_PIN D5 [get_ports {DATA_io[6]}]
set_property PACKAGE_PIN F6 [get_ports {DATA_io[5]}]
set_property PACKAGE_PIN G6 [get_ports {DATA_io[4]}]
set_property PACKAGE_PIN G1 [get_ports {DATA_io[3]}]
set_property PACKAGE_PIN H3 [get_ports {DATA_io[1]}]
set_property PACKAGE_PIN H4 [get_ports {DATA_io[0]}]
set_property PACKAGE_PIN H1 [get_ports {DATA_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BE_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BE_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BE_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BE_io[0]}]
set_property PACKAGE_PIN F5 [get_ports {BE_io[3]}]
set_property PACKAGE_PIN E3 [get_ports {BE_io[2]}]
set_property PACKAGE_PIN E4 [get_ports {BE_io[1]}]
set_property PACKAGE_PIN F4 [get_ports {BE_io[0]}]
set_property PACKAGE_PIN A4 [get_ports {DATA_io[18]}]




set_property PACKAGE_PIN P6 [get_ports In_Trig_P]
set_property PACKAGE_PIN P5 [get_ports In_Trig_N]
set_property IOSTANDARD BLVDS_25 [get_ports In_Trig_P]
set_property IOSTANDARD BLVDS_25 [get_ports In_Trig_N]

#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets In_Trig_P]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets In_Trig_N]


# set_property PACKAGE_PIN R5 [get_ports Out_Trig_P]
# set_property PACKAGE_PIN R4 [get_ports Out_Trig_N]
# set_property IOSTANDARD LVDS_25 [get_ports Out_Trig_N]
# set_property IOSTANDARD LVDS_25 [get_ports Out_Trig_P]





set_property PACKAGE_PIN L5 [get_ports Sys_clk_P]
set_property IOSTANDARD LVDS_25 [get_ports Sys_clk_P]
set_property IOSTANDARD LVDS_25 [get_ports Sys_clk_N]




set_property IOSTANDARD LVDS_25 [get_ports {ADC2_DATA_P[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC2_DATA_N[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC2_DATA_P[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC2_DATA_N[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC2_DATA_P[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC2_DATA_N[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC2_DATA_P[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC2_DATA_N[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC2_DATA_P[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC2_DATA_N[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC2_DATA_P[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC2_DATA_N[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC2_DATA_P[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC2_DATA_N[0]}]
set_property PACKAGE_PIN M2 [get_ports {ADC2_DATA_P[6]}]
set_property PACKAGE_PIN L6 [get_ports {ADC2_DATA_P[5]}]
set_property PACKAGE_PIN J2 [get_ports {ADC2_DATA_P[4]}]
set_property PACKAGE_PIN J3 [get_ports {ADC2_DATA_P[3]}]
set_property PACKAGE_PIN P3 [get_ports {ADC2_DATA_P[2]}]
set_property PACKAGE_PIN N8 [get_ports {ADC2_DATA_P[1]}]
set_property PACKAGE_PIN P7 [get_ports {ADC2_DATA_P[0]}]
set_property PACKAGE_PIN N6 [get_ports {ADC1_DATA_P[6]}]
set_property PACKAGE_PIN M4 [get_ports {ADC1_DATA_P[5]}]
set_property PACKAGE_PIN K7 [get_ports {ADC1_DATA_P[4]}]
set_property PACKAGE_PIN L2 [get_ports {ADC1_DATA_P[3]}]
set_property PACKAGE_PIN J5 [get_ports {ADC1_DATA_P[2]}]
set_property PACKAGE_PIN J7 [get_ports {ADC1_DATA_P[1]}]
set_property PACKAGE_PIN J8 [get_ports {ADC1_DATA_P[0]}]
set_property PACKAGE_PIN W12 [get_ports ADC2_SCLK]
set_property PACKAGE_PIN U11 [get_ports ADC2_SDATA]
set_property IOSTANDARD LVCMOS33 [get_ports ADC2_SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports ADC2_SDATA]
set_property PACKAGE_PIN U13 [get_ports ADC1_SCLK]
set_property PACKAGE_PIN U14 [get_ports ADC1_SDATA]
set_property PACKAGE_PIN W13 [get_ports ADC2_ADS5547_reset]
set_property PACKAGE_PIN U2 [get_ports ADC2_CLK_P]
set_property PACKAGE_PIN U1 [get_ports ADC2_CLK_N]
set_property PACKAGE_PIN V14 [get_ports ADC2_OVR]
set_property PACKAGE_PIN U12 [get_ports ADC2_SEN]
set_property IOSTANDARD LVCMOS33 [get_ports ADC2_ADS5547_reset]
set_property IOSTANDARD LVDS_25 [get_ports ADC2_CLK_N]
set_property IOSTANDARD LVDS_25 [get_ports ADC2_CLK_P]
set_property IOSTANDARD LVCMOS33 [get_ports ADC2_OVR]
set_property IOSTANDARD LVCMOS33 [get_ports ADC2_SEN]
set_property PACKAGE_PIN W16 [get_ports ADC1_ADS5547_reset]
set_property PACKAGE_PIN K4 [get_ports ADC1_CLK_P]
set_property PACKAGE_PIN K3 [get_ports ADC1_CLK_N]
set_property PACKAGE_PIN V16 [get_ports ADC1_OVR]
set_property PACKAGE_PIN V13 [get_ports ADC1_SEN]

create_clock -period 10.000 -name ADC1_CLK_P -waveform {0.000 5.000} [get_ports ADC1_CLK_P]
create_clock -period 10.000 -name CLK_i -waveform {0.000 5.000} [get_ports CLK_i]
create_clock -period 10.000 -name Sys_clk_P -waveform {0.000 5.000} [get_ports Sys_clk_P]

set_false_path -from [get_clocks clk_fpga_0] -to [get_clocks ADC1_CLK_P]
set_false_path -from [get_clocks CLK_i] -to [get_clocks clk_fpga_0]

set_false_path -from [get_clocks ADC1_CLK_P] -to [get_clocks clk_fpga_0]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_200M]
