set_property IOSTANDARD LVCMOS33 [get_ports {AD9516_SPI_tri_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD9516_SPI_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD9516_SPI_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD9516_SPI_tri_io[0]}]
set_property PACKAGE_PIN W11 [get_ports {AD9516_SPI_tri_io[0]}]
set_property PACKAGE_PIN V11 [get_ports {AD9516_SPI_tri_io[1]}]
set_property PACKAGE_PIN Y13 [get_ports {AD9516_SPI_tri_io[2]}]
set_property PACKAGE_PIN Y12 [get_ports {AD9516_SPI_tri_io[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports CLK_i]
set_property IOSTANDARD LVCMOS33 [get_ports {BE_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BE_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BE_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BE_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports WAKEUP_o]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[53]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[52]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[51]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[50]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[49]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[48]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[47]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[46]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[45]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[44]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[43]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[42]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[41]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[40]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[39]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[38]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[37]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[36]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[35]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[34]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[33]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[32]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ps_emio_tri_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ps_emio_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ps_emio_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ps_emio_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports FIXED_IO_ps_clk]
set_property IOSTANDARD LVCMOS33 [get_ports FIXED_IO_ps_porb]
set_property IOSTANDARD LVCMOS33 [get_ports FIXED_IO_ps_srstb]
set_property IOSTANDARD LVCMOS33 [get_ports OE_N_o]
set_property IOSTANDARD LVCMOS33 [get_ports RD_N_o]
set_property IOSTANDARD LVCMOS33 [get_ports RXF_N_i]
set_property IOSTANDARD LVCMOS33 [get_ports SIWU_N_o]
set_property IOSTANDARD LVCMOS33 [get_ports TXE_N_i]
set_property IOSTANDARD LVCMOS33 [get_ports WR_N_o]

create_clock -period 10.000 -name CLK_i -waveform {0.000 5.000} [get_ports CLK_i]
set_property IOSTANDARD LVCMOS33 [get_ports CLK_i]

set_property IOSTANDARD LVCMOS33 [get_ports RXF_N_i]

set_property IOSTANDARD LVCMOS33 [get_ports TXE_N_i]

set_property IOSTANDARD LVCMOS33 [get_ports WR_N_o]

set_property IOSTANDARD LVCMOS33 [get_ports RD_N_o]

set_property IOSTANDARD LVCMOS33 [get_ports OE_N_o]

set_property IOSTANDARD LVCMOS33 [get_ports WAKEUP_o]

set_property PACKAGE_PIN A4 [get_ports SIWU_N_o]
set_property IOSTANDARD LVCMOS33 [get_ports SIWU_N_o]

set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_o[*]}]

set_property PACKAGE_PIN D5 [get_ports {DATA_io[6]}]
set_property PACKAGE_PIN B2 [get_ports {DATA_io[11]}]
set_property PACKAGE_PIN B1 [get_ports {DATA_io[12]}]
set_property PACKAGE_PIN A2 [get_ports {DATA_io[13]}]
set_property PACKAGE_PIN A7 [get_ports {DATA_io[21]}]
set_property PACKAGE_PIN A6 [get_ports {DATA_io[22]}]
set_property PACKAGE_PIN B4 [get_ports {DATA_io[23]}]
set_property PACKAGE_PIN D7 [get_ports {DATA_io[27]}]
set_property PACKAGE_PIN D6 [get_ports {DATA_io[28]}]
set_property PACKAGE_PIN C8 [get_ports {DATA_io[29]}]
set_property PACKAGE_PIN B8 [get_ports {DATA_io[30]}]
set_property PACKAGE_PIN H6 [get_ports {DATA_io[31]}]

set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[*]}]
set_property PULLUP true [get_ports {DATA_io[0]}]
set_property PULLUP true [get_ports {DATA_io[1]}]
set_property PULLUP true [get_ports {DATA_io[2]}]
set_property PULLUP true [get_ports {DATA_io[3]}]
set_property PULLUP true [get_ports {DATA_io[4]}]
set_property PULLUP true [get_ports {DATA_io[5]}]
set_property PULLUP true [get_ports {DATA_io[6]}]
set_property PULLUP true [get_ports {DATA_io[7]}]
set_property PULLUP true [get_ports {DATA_io[8]}]
set_property PULLUP true [get_ports {DATA_io[9]}]
set_property PULLUP true [get_ports {DATA_io[10]}]
set_property PULLUP true [get_ports {DATA_io[11]}]
set_property PULLUP true [get_ports {DATA_io[12]}]
set_property PULLUP true [get_ports {DATA_io[13]}]
set_property PULLUP true [get_ports {DATA_io[14]}]
set_property PULLUP true [get_ports {DATA_io[15]}]
set_property PULLUP true [get_ports {DATA_io[16]}]
set_property PULLUP true [get_ports {DATA_io[17]}]
set_property PULLUP true [get_ports {DATA_io[18]}]
set_property PULLUP true [get_ports {DATA_io[19]}]
set_property PULLUP true [get_ports {DATA_io[20]}]
set_property PULLUP true [get_ports {DATA_io[21]}]
set_property PULLUP true [get_ports {DATA_io[22]}]
set_property PULLUP true [get_ports {DATA_io[23]}]
set_property PULLUP true [get_ports {DATA_io[24]}]
set_property PULLUP true [get_ports {DATA_io[25]}]
set_property PULLUP true [get_ports {DATA_io[26]}]
set_property PULLUP true [get_ports {DATA_io[27]}]
set_property PULLUP true [get_ports {DATA_io[28]}]
set_property PULLUP true [get_ports {DATA_io[29]}]
set_property PULLUP true [get_ports {DATA_io[30]}]
set_property PULLUP true [get_ports {DATA_io[31]}]

set_property IOSTANDARD LVCMOS33 [get_ports {BE_io[*]}]
set_property PACKAGE_PIN F4 [get_ports {BE_io[0]}]
set_property PACKAGE_PIN E4 [get_ports {BE_io[1]}]
set_property PACKAGE_PIN E3 [get_ports {BE_io[2]}]
set_property PACKAGE_PIN F5 [get_ports {BE_io[3]}]

set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS true [current_design]



set_property PACKAGE_PIN B6 [get_ports {DATA_io[26]}]
set_property PACKAGE_PIN B7 [get_ports {DATA_io[25]}]
set_property PACKAGE_PIN B3 [get_ports {DATA_io[24]}]
set_property PACKAGE_PIN C3 [get_ports {DATA_io[20]}]
set_property PACKAGE_PIN D3 [get_ports {DATA_io[19]}]
set_property PACKAGE_PIN A5 [get_ports {DATA_io[17]}]
set_property PACKAGE_PIN C5 [get_ports {DATA_io[16]}]
set_property PACKAGE_PIN F2 [get_ports {DATA_io[15]}]
set_property PACKAGE_PIN A1 [get_ports {DATA_io[14]}]
set_property PACKAGE_PIN G4 [get_ports {DATA_io[10]}]
set_property PACKAGE_PIN C1 [get_ports {DATA_io[9]}]
set_property PACKAGE_PIN D1 [get_ports {DATA_io[8]}]
set_property PACKAGE_PIN C4 [get_ports {DATA_io[7]}]
set_property PACKAGE_PIN F6 [get_ports {DATA_io[5]}]
set_property PACKAGE_PIN G6 [get_ports {DATA_io[4]}]
set_property PACKAGE_PIN G1 [get_ports {DATA_io[3]}]
set_property PACKAGE_PIN H1 [get_ports {DATA_io[2]}]
set_property PACKAGE_PIN H3 [get_ports {DATA_io[1]}]
set_property PACKAGE_PIN H4 [get_ports {DATA_io[0]}]
set_property PACKAGE_PIN D8 [get_ports {GPIO_o[1]}]
set_property PACKAGE_PIN E8 [get_ports {GPIO_o[0]}]
set_property PACKAGE_PIN C6 [get_ports CLK_i]
set_property PACKAGE_PIN G8 [get_ports OE_N_o]
set_property PACKAGE_PIN E7 [get_ports RD_N_o]
set_property PACKAGE_PIN G3 [get_ports RXF_N_i]
set_property PACKAGE_PIN E5 [get_ports TXE_N_i]
set_property PACKAGE_PIN G7 [get_ports WAKEUP_o]
set_property PACKAGE_PIN F7 [get_ports WR_N_o]

set_property PACKAGE_PIN H5 [get_ports {DATA_io[18]}]